# Generated by Django 2.1.5 on 2019-06-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingunit',
            name='election',
        ),
        migrations.AddField(
            model_name='election',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.VotingUnit'),
        ),
    ]
