# Generated by Django 2.1.5 on 2019-06-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190606_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingunit',
            name='voters_can_be_added',
            field=models.BooleanField(default=False),
        ),
    ]
