# Generated by Django 2.1.5 on 2019-06-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_votingunit_voters_can_be_added'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidatechoice',
            unique_together={('vote', 'value'), ('vote', 'candidate')},
        ),
    ]
