# Generated by Django 2.1.5 on 2019-06-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190608_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voting_power',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
    ]
